services:
  - type: web
    name: store-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SEED_DEFAULTS
        value: true
      - key: LOG_LEVEL
        value: info
      - key: LOG_TO_FILE
        value: false
      - key: CLIENT_URL
        value: https://store-frontend-a2i5.onrender.com
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: store-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://store-backend-qlr4.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
